AWSTemplateFormatVersion: "2010-09-09"
Description: "Config Rule to check if IAM roles have EC2 trust, instance profiles and required policy"

Parameters:
  SessionManagerPolicyName:
    Type: String
    Default: SessionManagerLogPolicy
    Description: Name of the policy to check for. Assumes policy is in the main path.

  AutoRemediation:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    Description: Enable or disable auto remediation

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Config Configuration"
        Parameters:
          - SessionManagerPolicyName
          - AutoRemediation

Resources:
  IAMRoleProfilePolicyRule:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: iam-ec2-role-has-required-policy
      Description: Checks if an AWS IAM EC2 role has the Session Manager custom policy attached. The rule is NON_COMPLIANT if the policy Session Manager custom is not attached to a IAM EC2 role with a instance profile.
      Scope:
        ComplianceResourceTypes:
          - "AWS::IAM::Role"
      Source:
        Owner: CUSTOM_POLICY
        CustomPolicyDetails:
          PolicyRuntime: "guard-2.x.x"
          EnableDebugLogDelivery: false
          PolicyText: !Sub |
            rule check_iam_role_ec2_profile_policy when
              resourceType == "AWS::IAM::Role" {
                when configuration.assumeRolePolicyDocument in /.*ec2\.amazonaws\.com.*/ {
                  when configuration.instanceProfileList not empty{
                    some configuration.attachedManagedPolicies[*].policyName == "${SessionManagerPolicyName}"
                  }
                }
              }
        SourceDetails:
          - EventSource: "aws.config"
            MessageType: "ConfigurationItemChangeNotification"
      MaximumExecutionFrequency: TwentyFour_Hours

  ConfigRemediationDocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "0.3"
        description: "Attaches SSM Session Manager policy to non-compliant instance profiles."
        assumeRole: "{{ AutomationAssumeRole }}"
        parameters:
          AutomationAssumeRole:
            type: String
            description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
            allowedPattern: ^arn:(aws|aws-cn|aws-us-gov)[a-z0-9-]*:iam::\d{12}:role\/[\w-\/.@+=,]{1,1017}$
          IAMResourceId:
            type: String
            description: (Required) IAM resource unique identifier for the IAM Role.
            allowedPattern: ^[\w+=,.@_-]{1,128}$
          SSMPolicyName:
            type: String
            default: !Ref SessionManagerPolicyName
            description: (Required) The name of the policy to attach to the instance profile.
          Partition:
            type: String
            description: (Required) The AWS partition (e.g., aws, aws-cn, aws-us-gov).
        outputs:
          - AttachIAMPolicyAndVerify.Output
        mainSteps:
          - name: AttachIAMPolicyAndVerify
            action: aws:executeScript
            timeoutSeconds: 600
            isEnd: true
            description: |
              ## AttachIAMPolicyAndVerify
              Attaches the specified managed policy to instance profiles without SSM Session Manager policy.
              ## Outputs
              * Output: Success message and HTTP response metadata or failure exception.
            inputs:
              Runtime: python3.11
              Handler: attach_policy_handler
              InputPayload:
                IAMResourceId: "{{ IAMResourceId }}"
                SSMPolicyName: "{{ SSMPolicyName }}"
                Partition: "{{ Partition }}"
              Script: |
                import json
                import boto3

                iam_client = boto3.client("iam")
                config_client = boto3.client("config")

                responses = {}
                responses["AttachRolePolicyResponses"] = []

                def get_role_name_from_id(role_id):
                    response = config_client.get_resource_config_history(
                        resourceType="AWS::IAM::Role", resourceId=role_id, limit=1
                    )

                    config_item = response["configurationItems"][0]
                    role_name = config_item.get("resourceName")
                    account_id = config_item.get("accountId")

                    configuration = json.loads(config_item.get("configuration"))
                    attached_managed_policies = configuration.get("attachedManagedPolicies", [])
                    return role_name, attached_managed_policies, account_id

                def attach_policy_handler(event, context):
                    try:
                        # Get role ID from event
                        role_id = event.get("IAMResourceId")

                        # Get policy name from event
                        ssm_policy_name = event.get("SSMPolicyName", "SessionManagerLogPolicy")

                        # Get role name from role ID
                        role_name, attached_managed_policies, account_id = get_role_name_from_id(role_id)

                        # Check if policy is already attached
                        policy_already_attached = False
                        for policy in attached_managed_policies:
                            if policy.get("policyName") == ssm_policy_name:
                                policy_already_attached = True
                                break

                        if policy_already_attached:
                            return {
                                "output": f"IAM Policy {ssm_policy_name} is already attached to role {role_name}.",
                                "http_response": responses,
                            }


                        # Attach the policy to the role (Assumes policy is in the main path)
                        partition = event.get("Partition", "aws")
                        policy_arn = f"arn:{partition}:iam::{account_id}:policy/{ssm_policy_name}"
                        response = iam_client.attach_role_policy(
                            RoleName=role_name, PolicyArn=policy_arn
                        )

                        responses["AttachRolePolicyResponses"].append(
                            {"RoleName": role_name, "Response": response}
                        )

                        # Verify the policy was attached
                        verification = iam_client.list_attached_role_policies(RoleName=role_name)
                        policy_attached = False

                        for policy in verification.get("AttachedPolicies", []):
                            if policy.get("PolicyArn") == policy_arn:
                                policy_attached = True
                                break

                        if not policy_attached:
                            error_msg = (
                                f"Failed to attach IAM Policy {policy_arn} to role {role_name}."
                            )
                            raise Exception(error_msg)

                        return {
                            "output": f"IAM Policy {policy_arn} attached successfully to role {role_name}.",
                            "http_response": responses,
                        }

                    except Exception as e:
                        error_msg = f"Unexpected error in attach_policy_handler: {str(e)}"
                        return {"output": error_msg, "http_response": responses}

            outputs:
              - Name: Output
                Selector: $.Payload
                Type: StringMap
      DocumentFormat: YAML
      DocumentType: Automation
      Name: Attach-ssm-policy-to-instance-profile

  AutomationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Sub ${AWS::AccountId}
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonSSMAutomationRole"
      Path: "/"

  AutomationServiceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Attach-ssm-policy-to-instance-profile
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: iam:ListAttachedRolePolicies
            Resource: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*"
          - Effect: Allow
            Action: iam:AttachRolePolicy
            Resource: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*"
            Condition:
              ArnEquals:
                "iam:PolicyARN": !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${SessionManagerPolicyName}"
          - Effect: Allow
            Action: config:GetResourceConfigHistory
            Resource: "*"
      Roles:
        - !Ref AutomationServiceRole

  ConfigRemediation:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      ConfigRuleName: iam-ec2-role-has-required-policy
      ResourceType: "AWS::IAM::Role"
      Automatic: !Ref AutoRemediation
      MaximumAutomaticAttempts: 5
      RetryAttemptSeconds: 60
      TargetId: !Ref ConfigRemediationDocument
      TargetType: "SSM_DOCUMENT"
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - !GetAtt AutomationServiceRole.Arn
        SSMPolicyName:
          StaticValue:
            Values:
              - !Ref SessionManagerPolicyName
        Partition:
          StaticValue:
            Values:
              - !Ref AWS::Partition
        IAMResourceId:
          ResourceValue:
            Value: RESOURCE_ID
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 10
          ErrorPercentage: 10
