Parameters:
  CWLogGroupName:
    Description: The name of the Amazon CloudWatch Logs (CloudWatch Logs) for session logs.
    Type: String
    Default: ssm-sessionmanager-logs
  PolicyName:
    Description: The name of the IAM managed policy to be created.
    Type: String
    Default: SessionManagerLogPolicy
Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      CWLogGroupName:
        default: "Session Manager CloudWatch Log Group Name:"
      PolicyName:
        default: "Session Manager Instance Profile Policy Name:"
Resources:
  SSMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref PolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:DescribeLogGroups
            Resource: "*"
          - Effect: Allow
            Action:
              - logs:DescribeLogStreams
            Resource: !Sub "arn:${AWS::Partition}:logs:*:${AWS::AccountId}:log-group:${CWLogGroupName}"
          - Effect: Allow
            Action:
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: !Sub "arn:${AWS::Partition}:logs:*:${AWS::AccountId}:log-group:${CWLogGroupName}:log-stream:*"
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource: !Sub "arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/*"
            Condition:
              ForAllValues:StringLike:
                "kms:ResourceAliases":
                  - "alias/session-manager/data"
              "Null":
                "kms:ResourceAliases": "false"
